export enum APP_EVENTS {
    WAITING_FOR_PLAYER = 'WAITING_FOR_PLAYER',
    ROUND_PREPARE = 'ROUND_PREPARE',
    DEPLOY_CHANNEL = 'DEPLOY_CHANNEL',
    CHANNEL_DEPLOYED = 'CHANNEL_DEPLOYED',
    CHANNEL_INIT = 'CHANNEL_INIT',
    PLAYER_READY = 'PLAYER_READY',
    ROUND_START = 'ROUND_START',
    CHALLENGE_START = 'CHALLENGE_START',
    PLAYER_INPUT = 'PLAYER_INPUT',
    CHALLENGE_END = 'CHALLENGE_END',
    CHANNEL_STATE_UPDATE = 'CHANNEL_STATE_UPDATE',
    CHANNEL_STATE_APPROVED = 'CHANNEL_STATE_APPROVED',
    ROUND_END = 'ROUND_END'
}